
import { Employee, ConfirmationStatus, UserRole, Recommendation, FinalDecision } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 1,
    name: "Alice Johnson",
    employeeId: "E1001",
    designation: "Software Engineer",
    department: "Technology",
    joiningDate: "2024-01-15",
    reportingManagerName: "Bob Williams",
    confirmationDueDate: "2024-07-15",
    status: ConfirmationStatus.PendingReportingManager,
    reportingManagerFeedback: null,
    deptHeadFeedback: null,
    hrHeadFeedback: null,
  },
  {
    id: 2,
    name: "Charlie Brown",
    employeeId: "E1002",
    designation: "Product Designer",
    department: "Design",
    joiningDate: "2024-01-20",
    reportingManagerName: "Bob Williams",
    confirmationDueDate: "2024-07-20",
    status: ConfirmationStatus.PendingDeptHead,
    reportingManagerFeedback: {
      strengths: "Excellent design skills and a great team player.",
      weaknesses: "Needs to be more proactive in meetings.",
      recommendation: Recommendation.Confirm,
      remarks: "Charlie has shown great potential and is a valuable asset to the team.",
      date: "2024-07-10",
    },
    deptHeadFeedback: null,
    hrHeadFeedback: null,
  },
  {
    id: 3,
    name: "Diana Prince",
    employeeId: "E1003",
    designation: "HR Executive",
    department: "Human Resources",
    joiningDate: "2024-01-10",
    reportingManagerName: "Eve Adams",
    confirmationDueDate: "2024-07-10",
    status: ConfirmationStatus.PendingHRHead,
    reportingManagerFeedback: {
      strengths: "Very organized and detail-oriented.",
      weaknesses: "Can improve on handling multiple high-priority tasks simultaneously.",
      recommendation: Recommendation.Confirm,
      remarks: "Solid performance.",
      date: "2024-07-01",
    },
    deptHeadFeedback: {
      decision: FinalDecision.Approve,
      remarks: "Agreed. Diana is a good fit for the company culture.",
      date: "2024-07-05",
    },
    hrHeadFeedback: null,
  },
  {
    id: 4,
    name: "Frank Miller",
    employeeId: "E1004",
    designation: "Marketing Specialist",
    department: "Marketing",
    joiningDate: "2023-12-01",
    reportingManagerName: "Grace Lee",
    confirmationDueDate: "2024-06-01",
    status: ConfirmationStatus.Confirmed,
    reportingManagerFeedback: {
      strengths: "Creative and effective campaign strategies.",
      weaknesses: "None to mention.",
      recommendation: Recommendation.Confirm,
      remarks: "Exceptional performance.",
      date: "2024-05-20",
    },
    deptHeadFeedback: {
      decision: FinalDecision.Approve,
      remarks: "Fully agree.",
      date: "2024-05-22",
    },
    hrHeadFeedback: {
      decision: FinalDecision.Approve,
      remarks: "Confirmation processed.",
      date: "2024-05-25",
    },
  },
  {
    id: 5,
    name: "George Costanza",
    employeeId: "E1005",
    designation: "Sales Associate",
    department: "Sales",
    joiningDate: "2024-01-05",
    reportingManagerName: "Grace Lee",
    confirmationDueDate: "2024-07-05",
    status: ConfirmationStatus.Terminated,
    reportingManagerFeedback: {
      strengths: "Good communication skills.",
      weaknesses: "Consistently failed to meet sales targets. Lacks initiative.",
      recommendation: Recommendation.Terminate,
      remarks: "Performance has not met expectations despite multiple feedback sessions.",
      date: "2024-06-25",
    },
    deptHeadFeedback: {
      decision: FinalDecision.Approve,
      remarks: "Termination is unfortunate but necessary. I approve the recommendation.",
      date: "2024-06-28",
    },
    hrHeadFeedback: {
      decision: FinalDecision.Approve,
      remarks: "Termination process initiated as per company policy.",
      date: "2024-06-30",
    },
  },
];

export const USER_ROLES: UserRole[] = [
    UserRole.ReportingManager,
    UserRole.DeptHead,
    UserRole.HRHead
];
